export { logsModule } from './module'
export type { LogsPublicApi, LoggerConfiguration } from './module'
export { logsExtension } from './domain/configuration'
export type { LogsInitConfig, LogsConfig, ConsoleApi, ReportType } from './domain/configuration'
export { Logger, StatusType, HandlerType } from './domain/logger'
export type { LogsMessage } from './domain/logger'
export { startProcessor } from './domain/processor'
export type { LogEvent, LogError } from './domain/processor'
export { createRateLimiter } from './domain/rateLimiter'
