export { takeFullSnapshot, takeNodeSnapshot } from './internalApi'
export { record } from './record'
export type { SerializationMetric, SerializationStats } from './serialization'
export { createSerializationStats, aggregateSerializationStats } from './serialization'
export { serializeNode, serializeDocument } from './serialization'
export { createElementsScrollPositions } from './elementsScrollPositions'
export type { ShadowRootsController } from './shadowRootsController'
