import { noop } from '@datadog/browser-core'
import { IncrementalSource, RecordType } from 'rum-events-format/session-replay-browser'
import type {
  AttributeMutation,
  BrowserChangeRecord,
  BrowserFullSnapshotRecord,
  BrowserIncrementalSnapshotRecord,
  BrowserRecord,
  RemovedNodeMutation,
} from 'rum-events-format/session-replay-browser'
import type { EmitRecordCallback, SerializeEvent } from './record.types'
import { createRecordingScope } from './recordingScope'
import type { RecordingScope } from './recordingScope'
import type { ShadowRootsController } from './shadowRootsController'
import {
  createChangeConverter,
  createCopyingNodeIdRemapper,
  serializeFullSnapshotAsChange,
  serializeMutationsAsChange,
} from './serialization'
import type { NodeId } from './itemIds'

/**
 * SerializationVerifier compares the output of the V1 and Change serialization
 * algorithms. It's designed to seamlessly add verification to existing test suites which
 * are written against the V1 serialization algorithm.
 *
 * To use it, create a SerializationVerifier configured with the same RecordingScope used
 * by the current test. The SerializationVerifier will automatically listen for V1
 * serializations being performed by the test code and will perform the corresponding
 * Change serialization. It will then convert the resulting BrowserChangeRecord to the old
 * V1 format and compare the results to verify that the two algorithms produce the same
 * output.
 */
export interface SerializationVerifier {
  stop(this: void): void
}

export type OnVerificationError = (message: string, context?: any) => void

export function createSerializationVerifier(
  scope: RecordingScope,
  onError: OnVerificationError
): SerializationVerifier {
  // Node id numbering differs between the V1 and Change serialization
  // algorithms, so if we want to be able to compare their output, we need to replace the
  // 'input' node ids in each Change record with the 'output' node ids produced by the V1
  // serialization algorithm. This NodeIdRemapper will handle that task.
  const nodeIdRemapper = createCopyingNodeIdRemapper()
  scope.nodeIds = nodeIdRemapper.outputNodeIds

  // Create a separate recording scope to use for Change serialization.
  const changeScope = createRecordingScope(scope.configuration, scope.elementsScrollPositions, {
    addShadowRoot: noop,
    removeShadowRoot: noop,
    flush: noop,
    stop: noop,
  } as ShadowRootsController)
  changeScope.nodeIds = nodeIdRemapper.inputNodeIds

  // Create the converter that we'll use to transform the records generated by Change
  // serialization into the V1 format.
  let converter = createChangeConverter()

  const { unsubscribe } = scope.serializeObservable.subscribe((event: SerializeEvent) => {
    let changeRecord: BrowserRecord | undefined
    const emitRecord: EmitRecordCallback = (record: BrowserRecord): void => {
      changeRecord = record
    }

    switch (event.type) {
      case 'full':
        // Create a new converter since we've transitioned to a new view.
        converter = createChangeConverter()

        serializeFullSnapshotAsChange(event.timestamp, event.kind, event.target, emitRecord, noop, changeScope)
        break

      case 'incremental':
        serializeMutationsAsChange(event.timestamp, event.target, emitRecord, noop, changeScope)
        break

      default:
        event satisfies never
        return
    }

    if (!changeRecord) {
      onError('No change record serialized', event)
      return
    }

    try {
      const v1Record = event.v1
      const convertedChangeRecord = converter.convert(changeRecord as BrowserChangeRecord, {
        nodeIdRemapper,
        timestamp: v1Record.timestamp,
      })

      verifySnapshotsMatch(v1Record, convertedChangeRecord, onError)
    } catch (error) {
      onError('Error verifying change record', error)
    }
  })

  return {
    stop: unsubscribe,
  }
}

function verifySnapshotsMatch(
  expectedRecord: BrowserFullSnapshotRecord | BrowserIncrementalSnapshotRecord,
  actualRecord: BrowserFullSnapshotRecord | BrowserIncrementalSnapshotRecord,
  onError: OnVerificationError
): void {
  if (
    expectedRecord.type !== RecordType.IncrementalSnapshot ||
    expectedRecord.data.source !== IncrementalSource.Mutation ||
    actualRecord.type !== RecordType.IncrementalSnapshot ||
    actualRecord.data.source !== IncrementalSource.Mutation
  ) {
    // We expect full snapshots to be byte-for-byte equivalent, full stop.
    verifyByteForByteEquivalence('full snapshot', expectedRecord, actualRecord, onError)
    return
  }

  // Verify that everything but the data is byte-for-byte equivalent.
  verifyByteForByteEquivalence(
    'incremental snapshot wrapper',
    { ...expectedRecord, data: null },
    { ...actualRecord, data: null },
    onError
  )

  // Within the data, verify that everything but attribute mutations and node remove
  // mutations are byte-for-byte equivalent.
  verifyByteForByteEquivalence(
    'incremental snapshot data (without attributes and removes)',
    { ...expectedRecord.data, attributes: null, removes: null },
    { ...actualRecord.data, attributes: null, removes: null },
    onError
  )

  // Verify that the attribute mutations are byte-for-byte equivalent except for order.
  const orderAttributeMutations = (a: AttributeMutation, b: AttributeMutation): number => a.id - b.id
  verifyByteForByteEquivalence(
    'incremental snapshot attribute mutations',
    expectedRecord.data.attributes.sort(orderAttributeMutations),
    actualRecord.data.attributes.sort(orderAttributeMutations),
    onError
  )

  // Gather the set of removes performed by V1 serialization.
  const expectedRemoves = expectedRecord.data.removes
  const expectedRemovedNodes = new Set<NodeId>()
  for (const remove of expectedRemoves) {
    expectedRemovedNodes.add(remove.id as NodeId)
  }

  // Gather the set of removes performed by Change serialization. Change serialization is
  // more conservative about remove reporting, so it will report some removes that V1
  // serialization deliberately skips. To paper over that difference, we filter out
  // removes that V1 serialization didn't also report.
  const actualRemoves: RemovedNodeMutation[] = actualRecord.data.removes.filter((remove) =>
    expectedRemovedNodes.has(remove.id as NodeId)
  )

  // Verify that the removes that remain are byte-for-byte equivalent.
  verifyByteForByteEquivalence('incremental snapshot removes', expectedRemoves, actualRemoves, onError)
}

function verifyByteForByteEquivalence(
  context: string,
  expected: unknown,
  actual: unknown,
  onError: OnVerificationError
): void {
  const expectedString = JSON.stringify(expected)
  const actualString = JSON.stringify(actual)
  if (actualString !== expectedString) {
    onError('Serialization mismatch', {
      context,
      mismatch: createSerializationMismatchContext(expectedString, actualString),
    })
  }
}

function createSerializationMismatchContext(expected: string, actual: string): Record<string, string> {
  const length = Math.min(expected.length, actual.length)
  try {
    let firstDifferenceIndex = 0
    while (firstDifferenceIndex < length && expected[firstDifferenceIndex] === actual[firstDifferenceIndex]) {
      firstDifferenceIndex++
    }
    return {
      expected: getStringNearPosition(expected, firstDifferenceIndex),
      actual: getStringNearPosition(actual, firstDifferenceIndex),
    }
  } catch (e) {
    return { firstDifferenceError: JSON.stringify(e) }
  }
}

function getStringNearPosition(str: string, index: number): string {
  const leftContextStart = Math.max(index - 50, 0)
  const rightContextEnd = Math.min(index + 150, str.length)
  return `${str.substring(leftContextStart, index)}(!)${str.substring(index, rightContextEnd)}`
}
