variables:
  CURRENT_STAGING: staging-23
  APP: 'browser-sdk'
  CURRENT_CI_IMAGE: 109
  BUILD_STABLE_REGISTRY: 'registry.ddbuild.io'
  CI_IMAGE: '$BUILD_STABLE_REGISTRY/ci/$APP:$CURRENT_CI_IMAGE'
  GIT_REPOSITORY: 'git@github.com:DataDog/browser-sdk.git'
  MAIN_BRANCH: 'main'
  NEXT_MAJOR_BRANCH: ''
  CHROME_PACKAGE_VERSION: 148.0.7778.96-1
  FF_TIMESTAMPS: 'true' # Enable timestamps for gitlab-ci logs

workflow:
  auto_cancel:
    on_new_commit: interruptible

cache:
  key:
    files:
      - yarn.lock
  paths:
    - .yarn/cache

stages:
  - task
  - ci-image
  - test
  - after-tests
  - browserstack
  - pre-deploy
  - deploy:canary
  - notify:canary
  - deploy
  - notify

.base-configuration:
  tags:
    - 'arch:amd64'
  image: $CI_IMAGE
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  retry:
    max: 2
    when:
      - runner_system_failure

########################################################################################################################
# Branch selection helpers
########################################################################################################################

.test-allowed-branches:
  except:
    refs:
      - /^release\//
      - schedules

.bs-allowed-branches:
  except:
    refs:
      - main
      - /^mq-working-branch-staging-[0-9]+-[a-z0-9]+$/
      - /^staging-[0-9]+$/
      - /^release\//
      - schedules
    variables:
      - $CI_COMMIT_REF_NAME == $NEXT_MAJOR_BRANCH

.feature-branches:
  except:
    refs:
      - main
      - tags
      - /^staging-[0-9]+$/
      - /^release\//
      - schedules
    variables:
      - $CI_COMMIT_REF_NAME == $NEXT_MAJOR_BRANCH

.next-major-branch:
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $NEXT_MAJOR_BRANCH

.staging:
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $CURRENT_STAGING

.main:
  only:
    refs:
      - main
  except:
    refs:
      - schedules
    variables:
      - $CI_COMMIT_TITLE =~ /^v[0-9.]+/

.tags:
  only:
    refs:
      - tags

###########################################################################################################################
# Resource allocation
###########################################################################################################################
.resource-allocation-4-cpus:
  variables:
    WORKERS: 2
    KUBERNETES_CPU_REQUEST: 4
    KUBERNETES_CPU_LIMIT: 4
    KUBERNETES_MEMORY_REQUEST: 16Gi
    KUBERNETES_MEMORY_LIMIT: 16Gi
    NODE_OPTIONS: '--max-old-space-size=16000'

########################################################################################################################
# CI image
########################################################################################################################

ci-image:
  stage: ci-image
  extends:
    - .base-configuration
    - .feature-branches
  when: manual
  tags: ['arch:amd64']
  image: $BUILD_STABLE_REGISTRY/images/docker:27.3.1
  id_tokens:
    DDSIGN_ID_TOKEN:
      aud: image-integrity
  script:
    - METADATA_FILE=$(mktemp)
    - PLAYWRIGHT_VERSION=$(jq -r '.devDependencies["@playwright/test"]' package.json)
    - >
      docker buildx build
      --platform linux/amd64
      --build-arg CHROME_PACKAGE_VERSION=$CHROME_PACKAGE_VERSION
      --build-arg PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION
      --tag $CI_IMAGE
      --push
      --metadata-file $METADATA_FILE
      .
    - ddsign sign $CI_IMAGE --docker-metadata-file $METADATA_FILE

########################################################################################################################
# Tests
########################################################################################################################

code-review:
  stage: test
  extends:
    - .base-configuration
    - .feature-branches
  interruptible: true
  artifacts:
    paths:
      - .cr-agent/sessions/
    when: always
    expire_in: 1 week
  before_script:
    - eval $(ssh-agent -s)
    - yarn
    - node -e 'import { initGitConfig } from "./scripts/lib/gitUtils.ts"; initGitConfig()'
  script:
    - ./.cr-agent/run.sh
