variables:
  APP: 'browser-sdk'
  CURRENT_CI_IMAGE: 104
  BUILD_STABLE_REGISTRY: 'registry.ddbuild.io'
  CI_IMAGE: '$BUILD_STABLE_REGISTRY/ci/$APP:$CURRENT_CI_IMAGE'
  FF_TIMESTAMPS: 'true'

stages:
  - test

.base-configuration:
  tags:
    - 'arch:amd64'
  image: $CI_IMAGE
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  retry:
    max: 2
    when:
      - runner_system_failure

hello-world:
  extends:
    - .base-configuration
  stage: test
  script:
    - yarn
    - yarn build:bundle
    - du -sh packages/rum/bundle/datadog-rum.js
