variables:
  APP: 'browser-sdk'
  CURRENT_CI_IMAGE: 106
  BUILD_STABLE_REGISTRY: 'registry.ddbuild.io'
  CI_IMAGE: '$BUILD_STABLE_REGISTRY/ci/$APP:$CURRENT_CI_IMAGE'
  FF_TIMESTAMPS: 'true'

stages:
  - test

e2e-partitioned-cookie:
  tags:
    - 'arch:amd64'
  image: $CI_IMAGE
  stage: test
  script:
    - yarn
    - yarn build:bundle
    - FORCE_COLOR=1 yarn playwright test --config test/e2e/playwright.local.config.ts --project chromium -g 'with different usePartitionedCrossSiteSessionCookie values bundle'
