yarnPath: .yarn/releases/yarn-4.7.0.cjs
defaultSemverRangePrefix: ''
nodeLinker: node-modules

# Gitlab artifacts are only supported folders relative to the repository. Disable global cache so yarn will store the cache in .yarn/cache.
# See https://docs.gitlab.com/ee/ci/jobs/job_artifacts.html#create-job-artifacts
# See https://yarnpkg.com/configuration/yarnrc#enableGlobalCache
enableGlobalCache: false
