export { createDatadogReactRouter } from '../react-router/lib/createDatadogReactRouter'
export { WithDatadogRoutesTracker } from '../react-router/components/WithDatadogRoutesTracker'
export { DatadogProvider } from '../components/DatadogProvider'
export { useRoutesWithTracker } from '../react-router/hooks/useRoutesWithTracker'
export { DatadogErrorTracker } from '../error-tracking/components/DatadogErrorTracker'
export { WithDatadogRecorder } from '../performance/WithDatadogRecorder'
export { ReactRecorder } from '../performance/ReactRecorder'
