export { nextjsPlugin, onRouterTransitionStart } from '../domain/nextjsPlugin'
export type { NextjsPlugin } from '../domain/nextjsPlugin'
export { DatadogAppRouter } from '../domain/nextJSRouter/datadogAppRouter'
export { addNextjsError } from '../domain/error/addNextjsError'
export { NextjsErrorBoundary } from '../domain/error/nextjsErrorBoundary'
export type { NextjsErrorBoundaryProps, NextjsErrorBoundaryFallback } from '../domain/error/nextjsErrorBoundary'
export { DatadogPagesRouter } from '../domain/nextJSRouter/datadogPagesRouter'
