export { DatadogRumProvider } from './datadogRumProvider'
export type { DatadogRumProviderProps } from './datadogRumProvider'
export { usePathnameTracker, startNextjsView, normalizeViewName } from './viewTracking'
// export { initDatadogRum } from './initDatadogRum'
export type { NextjsRumConfig } from './types'
