export { getElementInputValue } from './serializationUtils'
export { serializeDocument } from './serializeDocument'
export { serializeNode } from './serializeNode'
export { serializeAttribute } from './serializeAttribute'
export { createSerializationStats, updateSerializationStats, aggregateSerializationStats } from './serializationStats'
export type { SerializationMetric, SerializationStats } from './serializationStats'
export { serializeInTransaction, SerializationKind } from './serializationTransaction'
export type { SerializationTransaction, SerializationTransactionCallback } from './serializationTransaction'
