export type { ChangeDecoder } from './changeDecoder'
export { createChangeDecoder } from './changeDecoder'
export { createChildInsertionCursor, createRootInsertionCursor } from './insertionCursor'
export { getElementInputValue } from './serializationUtils'
export { serializeFullSnapshotAsChange } from './serializeFullSnapshotAsChange'
export { serializeMutationsAsChange } from './serializeMutationsAsChange'
export { serializeNodeAsChange } from './serializeNodeAsChange'
export { serializeAttribute } from './serializeAttribute'
export { createSerializationStats, updateSerializationStats, aggregateSerializationStats } from './serializationStats'
export type { SerializationMetric, SerializationStats } from './serializationStats'
export { serializeChangesInTransaction, SerializationKind } from './serializationTransaction'
export type { ChangeSerializationTransaction } from './serializationTransaction'
