export { startSegmentCollection, setSegmentBytesLimit } from './segmentCollection'
export { SEGMENT_BYTES_LIMIT } from './segmentCollection'
export type { BrowserSegmentMetadataAndSegmentSizes, ReplayPayload } from './buildReplayPayload'
export { startSegmentTelemetry } from './startSegmentTelemetry'
export { startCanvasResourceCollection } from './canvasResourceCollection'
export type { ResourceCollector } from './canvasResourceCollection'
