export type { ChangeDecoder } from './changeDecoder'
export { createChangeDecoder } from './changeDecoder'
export { createChildInsertionCursor, createRootInsertionCursor } from './insertionCursor'
export { getElementInputValue } from './serializationUtils'
export { serializeFullSnapshot } from './serializeFullSnapshot'
export { serializeMutations } from './serializeMutations'
export { serializeNode } from './serializeNode'
export { serializeAttribute } from './serializeAttribute'
export { createSerializationStats, updateSerializationStats, aggregateSerializationStats } from './serializationStats'
export type { SerializationMetric, SerializationStats } from './serializationStats'
export { serializeInTransaction, SerializationKind } from './serializationTransaction'
export type { SerializationTransaction } from './serializationTransaction'
