import { monitor } from '@datadog/js-core/monitor'
import { noop } from '@datadog/browser-core'
import { timeStampNow } from '@datadog/js-core/time'
import type { RumMutationRecord } from '@datadog/browser-rum-core'
import { getMutationObserverConstructor } from '@datadog/browser-rum-core'
import type { RecordingScope } from '../recordingScope'
import { isCanvasElement, isCanvasSizeAttribute } from '../canvas/canvasUtils'
import { createMutationBatch } from '../mutationBatch'
import type { EmitRecordCallback, EmitResourceCallback, EmitStatsCallback } from '../record.types'
import { serializeMutations } from '../serialization'
import type { Tracker } from './tracker.types'

export type MutationTracker = Tracker & { flush: () => void; notifyContentMutated: () => void }

/**
 * Buffers and aggregate mutations generated by a MutationObserver into MutationPayload
 */
export function trackMutation(
  target: Node,
  emitRecord: EmitRecordCallback,
  emitResource: EmitResourceCallback,
  emitStats: EmitStatsCallback,
  scope: RecordingScope
): MutationTracker {
  const MutationObserver = getMutationObserverConstructor()
  if (!MutationObserver) {
    return { stop: noop, flush: noop, notifyContentMutated: noop }
  }

  const mutationBatch = createMutationBatch((mutations) => {
    const remainingMutations = observer.takeRecords() as RumMutationRecord[]
    prepareCanvasBitmapResets(remainingMutations, scope)
    serializeMutations(timeStampNow(), mutations.concat(remainingMutations), emitRecord, emitResource, emitStats, scope)
  })

  const observer = new MutationObserver(
    monitor((mutations) => {
      // Prepare resize resets before batching so delayed serialization does not discard a newer WebGL snapshot.
      prepareCanvasBitmapResets(mutations, scope)
      mutationBatch.addMutations(mutations)
    })
  )

  observer.observe(target, {
    attributeOldValue: true,
    attributes: true,
    characterData: true,
    characterDataOldValue: true,
    childList: true,
    subtree: true,
  })

  return {
    stop: () => {
      observer.disconnect()
      mutationBatch.stop()
    },
    flush: () => {
      mutationBatch.flush()
    },
    notifyContentMutated: mutationBatch.notifyContentMutated,
  }
}

function prepareCanvasBitmapResets(mutations: RumMutationRecord[], scope: RecordingScope) {
  const resizedCanvases = new Set<HTMLCanvasElement>()

  for (const mutation of mutations) {
    if (
      mutation.type === 'attributes' &&
      mutation.attributeName !== null &&
      isCanvasElement(mutation.target) &&
      isCanvasSizeAttribute(mutation.attributeName) &&
      scope.nodeIds.get(mutation.target) !== undefined
    ) {
      resizedCanvases.add(mutation.target)
    }
  }

  resizedCanvases.forEach((canvas) => scope.canvasManager.prepareCanvasBitmapReset(canvas))
}
