import { monitor, noop } from '@datadog/browser-core'
import { timeStampNow } from '@datadog/js-core/time'
import type { RumMutationRecord } from '@datadog/browser-rum-core'
import { getMutationObserverConstructor } from '@datadog/browser-rum-core'
import type { RecordingScope } from '../recordingScope'
import { createMutationBatch } from '../mutationBatch'
import type { EmitRecordCallback, EmitStatsCallback } from '../record.types'
import { serializeMutations } from '../serialization'
import type { Tracker } from './tracker.types'
import { markCanvasDirtyFromMutationRecords } from './trackCanvas'

export type MutationTracker = Tracker & { flush: () => void }

/**
 * Buffers and aggregate mutations generated by a MutationObserver into MutationPayload
 */
export function trackMutation(
  target: Node,
  emitRecord: EmitRecordCallback,
  emitStats: EmitStatsCallback,
  scope: RecordingScope
): MutationTracker {
  const MutationObserver = getMutationObserverConstructor()
  if (!MutationObserver) {
    return { stop: noop, flush: noop }
  }

  const mutationBatch = createMutationBatch((mutations) => {
    // Process mutations still queued in the observer so canvas changes are tracked before flushing.
    const queuedMutations = observer.takeRecords() as RumMutationRecord[]
    markCanvasDirtyFromMutationRecords(queuedMutations, scope.canvasManager)
    serializeMutations(timeStampNow(), mutations.concat(queuedMutations), emitRecord, emitStats, scope)
  })

  const observer = new MutationObserver(
    monitor((mutations) => {
      // Keep the canvas manager in sync with DOM mutations so unchanged canvases can be skipped.
      markCanvasDirtyFromMutationRecords(mutations, scope.canvasManager)
      mutationBatch.addMutations(mutations)
    })
  )

  observer.observe(target, {
    attributeOldValue: true,
    attributes: true,
    characterData: true,
    characterDataOldValue: true,
    childList: true,
    subtree: true,
  })

  return {
    stop: () => {
      observer.disconnect()
      mutationBatch.stop()
    },
    flush: () => {
      mutationBatch.flush()
    },
  }
}
