export { takeFullSnapshot, takeNodeSnapshot } from './internalApi'
export { record } from './record'
export type { ChangeDecoder } from './encoding'
export { createChangeDecoder } from './encoding'
export type { SerializationMetric, SerializationStats } from './serialization'
export { aggregateSerializationStats, createSerializationStats } from './serialization'
export { createElementsScrollPositions } from './elementsScrollPositions'
export type { ShadowRootsController } from './shadowRootsController'
