stages:
  - pre-notify
  - deploy
  - post-notify

.base-configuration:
  tags: ['runner:main', 'size:large']
  image: $CI_IMAGE

.deploy-prod:
  stage: deploy
  script:
    - export BUILD_MODE=release
    - VERSION=$(node -p -e "require('./lerna.json').version")
    - yarn
    - yarn build:bundle
    - node ./scripts/deploy/deploy-prod-dc.js v${VERSION%%.*} $UPLOAD_PATH true

step-1_deploy-prod-minor-dcs:
  when: manual
  allow_failure: false
  extends:
    - .base-configuration
    - .deploy-prod
  variables:
    UPLOAD_PATH: us3,us5,ap1

step-2_deploy-prod-eu1:
  needs:
    - step-1_deploy-prod-minor-dcs
  extends:
    - .base-configuration
    - .deploy-prod
  variables:
    UPLOAD_PATH: eu1

step-3_deploy-prod-us1:
  needs:
    - step-2_deploy-prod-eu1
  extends:
    - .base-configuration
    - .deploy-prod
  variables:
    UPLOAD_PATH: us1

step-4_deploy-prod-gov:
  needs:
    - step-3_deploy-prod-us1
  extends:
    - .base-configuration
    - .deploy-prod
  variables:
    UPLOAD_PATH: root

step-5_publish-npm:
  needs:
    - step-4_deploy-prod-gov
  stage: deploy
  extends:
    - .base-configuration
  allow_failure: false
  script:
    - yarn
    - node ./scripts/deploy/publish-npm.js

step-6_publish-developer-extension:
  needs:
    - step-5_publish-npm
  stage: deploy
  extends:
    - .base-configuration
  allow_failure: false
  script:
    - yarn
    - node ./scripts/deploy/publish-developer-extension.js

########################################################################################################################
# Notify
########################################################################################################################

include: 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

.prepare_notification:
  extends: .slack-notifier-base
  before_script:
    - COMMIT_MESSAGE=`git show-branch --no-name HEAD`
    - BUILD_URL="$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"
    - COMMIT_URL="$CI_PROJECT_URL/commits/$CI_COMMIT_SHA"

notify-deploy-ready:
  stage: pre-notify
  extends:
    - .prepare_notification
  script:
    - 'MESSAGE_TEXT=":i: $CI_PROJECT_NAME <$BUILD_URL|$COMMIT_MESSAGE> ready to be deployed *automatically* to :datadog:"'
    - postmessage "#browser-sdk-deploy" "$MESSAGE_TEXT"

notify-deploy-success:
  stage: post-notify
  needs:
    - step-6_publish-developer-extension
  extends:
    - .prepare_notification
  script:
    - 'MESSAGE_TEXT=":rocket: $CI_PROJECT_NAME <$COMMIT_URL|$COMMIT_MESSAGE> *automatically* deployed to :earth_americas:."'
    - postmessage "#browser-sdk-deploy" "$MESSAGE_TEXT"
    - postmessage "#rum-browser-sdk-ops" "$MESSAGE_TEXT"

notify-deploy-failure:
  stage: post-notify
  extends:
    - .prepare_notification
  when: on_failure
  script:
    - 'MESSAGE_TEXT=":host-red: $CI_PROJECT_NAME *automatic* deployment of <$BUILD_URL|$COMMIT_MESSAGE> failed."'
    - postmessage "#browser-sdk-deploy" "$MESSAGE_TEXT"
