#!/bin/bash

set -euo pipefail

PATH="$PATH:node_modules/.bin"

main () {
  if [[ $# -lt 1 ]]; then
    cmd_help
  fi

  local command="cmd_$1"
  shift

  "$command" "$@"
}

cmd_help () {
  local available_commands=$(set | perl -nle'print $& while m{^cmd_\K\w+}g')
  echo -e "Available commands:\n$available_commands"
  exit 1
}

cmd_typecheck () {
  local project_path="${1}"
  tsc -p "$project_path" --noEmit true
}

cmd_lint () {
  local project_path="${1}"
  eslint "$project_path"
}

cmd_init_submodule () {
  git submodule update --init
}

cmd_update_submodule () {
  git submodule update --init
  git submodule update --remote
}

# needed because using fork instead of the npm package
# TODO remove me when json-schema-to-typescript natively supports readOnly
cmd_build_json2type () {
  cd ./node_modules/json-schema-to-typescript
  rm -rf dist
  # due to installation on node_modules, some of these steps can fail
  # built version still behaves correctly though
  set +e
  npm i
  npm run clean

  # With yarn 3, the 'test/' folder is not present, so all built files are put directly in the
  # 'dist/' folder instead of 'dist/src/'.
  #
  # Using an explicit '--rootDir' fixes this issue.
  npm exec -- tsc --declaration --rootDir .

  set -e
}

cmd_build_extensions () {
  node ./scripts/extensions/build-extensions.js
}

cmd_release () {
  [[ `git branch --show-current` != "main" ]] || fail 'please do not release from `main` branch'
  # We should publish all packages regardless of if there are changes in each.
  # --force-publish will skip the `lerna changed` check for changed packages
  # https://github.com/lerna/lerna/tree/main/libs/commands/version#--force-publish
  yarn lerna version --exact --force-publish
}

cmd_version () {
  node ./scripts/release/generate-changelog
  node ./scripts/release/update-peer-dependency-versions.js
  lerna run pack --stream
  # keep test apps lockfiles up to date
  for app_dir in test/apps/*; do
    cd "$app_dir"
    yarn up
    git add yarn.lock
    cd - > /dev/null
  done
}

cmd_woke () {
  command -v woke || fail 'woke not installed, see https://github.com/get-woke/woke#installation'
  woke --exit-1-on-failure
}

cmd_check_server_side_rendering_compatibility () {
  yarn build
  yarn lerna run pack --stream
  cd test/apps/vanilla
  rm -rf node_modules
  yarn install --no-immutable
  yarn compat:ssr || fail 'server side rendering compatibility broken'
}

fail () {
  echo
  echo "❌ ${1}"
  echo

  exit 1
}

main "$@"
