title: 'Datadog Browser SDK API Reference'
description: 'API documentation for Datadog Browser SDK packages'

# Build settings
markdown: kramdown

# GitHub Pages settings
baseurl: '/browser-sdk'
url: 'https://datadoghq.dev'

# Plugins
plugins:
  - jekyll-feed

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  parse_span_html: true
  html_to_native: true
  enable_coderay: false
  math_engine: null
