title: 'Datadog Browser SDK API Reference'
description: 'API documentation for Datadog Browser SDK packages'

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages settings
baseurl: '/browser-sdk'
url: 'https://datadoghq.dev'

# Plugins
plugins:
  - jekyll-feed

# Include markdown files
include:
  - '*.md'

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - CHANGELOG.md
  - node_modules/
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
