source "https://rubygems.org"

# GitHub Pages gem - inclut Jekyll et tous les plugins supportés
gem "github-pages", group: :jekyll_plugins

# Windows et JRuby support
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby] 