issuer: https://gitlab.ddbuild.io

subject_pattern: 'project_path:DataDog/browser-sdk:ref_type:branch:ref:main'

claim_pattern:
  project_path: 'DataDog/browser-sdk'
  ref_type: 'branch'
  ref: 'main'

permissions:
  pull_requests: write
