name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

jobs:
  pre-notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_deploy == 'yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Prepare notification
        run: |
          COMMIT_MESSAGE=$(git show-branch --no-name HEAD)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "BUILD_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_ENV

      - name: Notify deployment ready
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'browser-sdk-deploy'
          payload: |
            {
              "text": ":i: ${{ github.repository }} <${{ env.BUILD_URL }}|${{ env.COMMIT_MESSAGE }}> ready to be deployed *manually* to :datadog:"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn

      - name: Publish to NPM
        run: node ./scripts/deploy/publish-npm.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish-developer-extension:
  #   needs: publish-npm
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: yarn

  #     - name: Publish developer extension
  #       run: node ./scripts/deploy/publish-developer-extension.js
  #       env:
  #         CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
  #         CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
  #         CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
  #         CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

  post-notify-success:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare notification
        run: |
          COMMIT_MESSAGE=$(git show-branch --no-name HEAD)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_ENV

      - name: Notify deployment success
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'browser-sdk-deploy'
          payload: |
            {
              "text": ":rocket: ${{ github.repository }} <${{ env.COMMIT_URL }}|${{ env.COMMIT_MESSAGE }}> *manually* deployed to :earth_americas:."
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify ops team
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'rum-browser-sdk-ops'
          payload: |
            {
              "text": ":rocket: ${{ github.repository }} <${{ env.COMMIT_URL }}|${{ env.COMMIT_MESSAGE }}> *manually* deployed to :earth_americas:."
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  post-notify-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare notification
        run: |
          COMMIT_MESSAGE=$(git show-branch --no-name HEAD)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "BUILD_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Notify deployment failure
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: 'browser-sdk-deploy'
          payload: |
            {
              "text": ":host-red: ${{ github.repository }} *manual* deployment of <${{ env.BUILD_URL }}|${{ env.COMMIT_MESSAGE }}> failed."
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
