export { startSegmentCollection, setSegmentBytesLimit } from './segmentCollection'
export { DeflateWorker, DeflateWorkerListener } from './deflateWorker'
export { startDeflateWorker } from './startDeflateWorker'
export { SEGMENT_BYTES_LIMIT } from './segmentCollection'
export type { BrowserSegmentMetadataAndSegmentSizes } from './buildReplayPayload'
